config/routes.rb
Spruce::Application.routes.draw do
  constraints format: "html" do
    # authentication
    delete :logout, to: "sessions#destroy", as: :logout
    get    :login,  to: "sessions#new",     as: :login
    post   :login,  to: "sessions#create"

    # signup & activation
    get  :signup, to: "users#new", as: :signup
    post :signup, to: "users#create"
    get "/users/:token/activate", to: "users#activate", as: :activate,
      constraints: {token: /[A-z0-9]+/}

    # reset password
    resources :password_resets,
      param:  :token,
      except: [:index, :show, :destroy],
      constraints: {token: /[A-z0-9]+/}

    # versions
    constraints id: /[0-9]+/, type: /b|l/ do
      get  "/v/:id/:type/revert", to: "versions#revert", as: :revert_version,
        constraints: RevertConstraint.new
      post "/v/:id/:type/revert", to: "versions#restore",
        constraints: RevertConstraint.new
    end

    # pages
    get :introduction, to: "pages#introduction"
    get :changelog,    to: "pages#changelog"
    get :syntax,       to: "pages#syntax"
  end

  # nodes and notes
  constraints id: /[0-9]+/ do
    constraints format: /html|txt/ do
      resources :nodes, path: "b", shallow: true, only: :index
    end

    resources :nodes, path: "b", shallow: true, only: :none do
      constraints format: "html" do
        resources :nodes, path: "b",
          except: [:index, :destroy, :show], with: [:delete]
        resources :notes, path: "l",
          except: [:index, :destroy, :show], with: [:delete]
      end

      constraints format: /html|txt/ do
        resources :nodes, path: "b", only: [:show]
        resources :notes, path: "l", only: [:show]
      end
    end
  end

  constraints format: "xml" do
    get :sitemap, to: "sitemap#index"
  end

  root "pages#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
  before_filter :load_user_from_token, :only => [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(:email => user_params[:email])
    if @user.valid_attribute?(:email, %w[taken])
      @user = User.find_by_email(user_params[:email])
      @user.deliver_reset_password_instructions! if @user
      redirect_to root_url,
        :notice => "Instructions have been sent to your email :)"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.assign_attributes(user_params)
    if @user.valid? && @user.change_password!(user_params[:password])
      redirect_to root_url,
        :notice => "Password was successfully updated !"
    else
      render :edit
    end
  end

  private

    def load_user_from_token
      logout
      @token = params[:token]
      @user = User.load_from_reset_password_token(@token)
      unless @user
        not_authenticated
        flash.now.alert = "Invalid token :-p"
      end
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.slim
#password_resets
  h2 New Password
  - if @user.errors.any?
    = render "shared/errors", resource: @user
  = form_for @user, url: password_reset_path(@token), html: {method: :put, id: "user_email"} do |f|
    .field
      = f.label :email
      p.user_email= @user.email
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = hidden_field_tag :token, @token
    .actions
      = f.submit "Update"

app/views/password_resets/new.html.slim
#password_resets
  h2 Forgot Password?
  - if @user.errors.any?
    = render "shared/errors", resource: @user
  = form_for @user, url: password_resets_path, html: {method: :post} do |f|
    .field
      = f.label :email
      = f.text_field :email
    .actions
      = f.submit "Reset"