config/routes.rb
Spruce::Application.routes.draw do
  constraints format: "html" do
    # authentication
    delete :logout, to: "sessions#destroy", as: :logout
    get    :login,  to: "sessions#new",     as: :login
    post   :login,  to: "sessions#create"

    # signup & activation
    get  :signup, to: "users#new", as: :signup
    post :signup, to: "users#create"
    get "/users/:token/activate", to: "users#activate", as: :activate,
      constraints: {token: /[A-z0-9]+/}

    # reset password
    resources :password_resets,
      param:  :token,
      except: [:index, :show, :destroy],
      constraints: {token: /[A-z0-9]+/}

    # versions
    constraints id: /[0-9]+/, type: /b|l/ do
      get  "/v/:id/:type/revert", to: "versions#revert", as: :revert_version,
        constraints: RevertConstraint.new
      post "/v/:id/:type/revert", to: "versions#restore",
        constraints: RevertConstraint.new
    end

    # pages
    get :introduction, to: "pages#introduction"
    get :changelog,    to: "pages#changelog"
    get :syntax,       to: "pages#syntax"
  end

  # nodes and notes
  constraints id: /[0-9]+/ do
    constraints format: /html|txt/ do
      resources :nodes, path: "b", shallow: true, only: :index
    end

    resources :nodes, path: "b", shallow: true, only: :none do
      constraints format: "html" do
        resources :nodes, path: "b",
          except: [:index, :destroy, :show], with: [:delete]
        resources :notes, path: "l",
          except: [:index, :destroy, :show], with: [:delete]
      end

      constraints format: /html|txt/ do
        resources :nodes, path: "b", only: [:show]
        resources :notes, path: "l", only: [:show]
      end
    end
  end

  constraints format: "xml" do
    get :sitemap, to: "sitemap#index"
  end

  root "pages#index"
end

app/views/shared/_errors.html.slim
.error-messages
  ul
    - resource.errors.each do |attr, e|
      li.alert
        = resource.errors.full_message(attr, e.is_a?(Hash) ? e[:message] : e)

app/views/shared/_flash.html.slim
.flash-messages
  ul
    - flash.each do |name, message|
      li(class="#{name}")= message.html_safe

app/views/shared/_navigation.html.slim
ruby:
  current_node = node.new_record? ? parent : node
  styles       = parenthesis_styles
p.navigation
  | (
  span(class=styles[:node][:edit])
    | (
  - if controller_name == "nodes" && !current_node.root?
    - if action_name.in?(%w[show])
      = link_to "edit", edit_node_path(node)
    - elsif action_name.in?(%w[edit update])
      span.title EDIT
    - elsif action_name.in?(%w[new create])
      = link_to "edit", edit_node_path(node.parent)
    - else
      | edit
  - elsif note && action_name.in?(%w[new create show edit update]) && !current_node.root?
    = link_to "edit", edit_node_path(node)
  - else
    | edit
  | &nbsp;
  span(class=styles[:node][:show])
    | (
  - unless node.new_record?
    - if controller_name == "nodes" && action_name == "show"
      span.title SHOW
    - elsif action_name.in?(%w[show edit update])
      = link_to "show", node
    - elsif note && action_name.in?(%w[new create edit update])
      = link_to "show", node
    - else
      | show
    | &nbsp;
    span(class=styles[:node][:new])
      | (
    = link_to "new 'branch", new_node_node_path(node)
    span(class=styles[:node][:new])
      | )
    span(class=styles[:node][:show])
      | )
    span(class=styles[:node][:edit])
      | )
    |&nbsp;
    span(class=styles[:note][:edit])
      | (
    - if controller_name == "notes"
      - if action_name == "show"
        = link_to "edit", edit_note_path(note)
      - elsif action_name.in?(%w[edit update])
        span.title EDIT
      - else
        | edit
    - else
      | edit
    | &nbsp;
    span(class=styles[:note][:show])
      | (
    - if note && !note.new_record?
      - if action_name == "show"
        span.title SHOW
      - elsif action_name.in?(%w[edit update])
        = link_to "show", note
      - else
        | show
    - else
      | show
    | &nbsp;
    span(class=styles[:note][:new])
      | (
    - if controller_name == "notes" && action_name.in?(%w[new create])
      span.title NEW 'LEAF
    - else
      = link_to "new 'leaf", new_node_note_path(node)
    span(class=styles[:note][:new])
      | )
    span(class=styles[:note][:show])
      | )
    span(class=styles[:note][:edit])
      | )
  - else
    = link_to "show", node.parent
    | &nbsp;
    span(class=styles[:node][:new])
      | (
    span.title NEW 'BRANCH
    span(class=styles[:node][:new])
      | )
    span(class=styles[:node][:show])
      | )
    span(class=styles[:node][:edit])
      | )
    | &nbsp;
    | (
    | edit&nbsp;
    span(class=styles[:note][:show])
      | (
    - if note && !note.new_record?
      - if action_name == "show"
        span.title SHOW
      - elsif action_name.in?(%w[edit update])
        = link_to "show", note
      - else
        | show
    - else
      | show
    | &nbsp;
    | (
    = link_to "new 'leaf", new_node_note_path(current_node)
    | )
    span(class=styles[:note][:show])
      | )
    | )
  | )

p.path
  - if current_node.new_record? || !current_node.root? || controller_name == "notes"
    == render_paths(current_node.paths)
    - if action_name.in?(%w[new create]) || (controller_name == "notes" && !action_name.in?(%w[index show]))
      | &nbsp;/
  - else
    | /&nbsp;
    span.pwd root