config/routes.rb
Spruce::Application.routes.draw do
  constraints format: "html" do
    # authentication
    delete :logout, to: "sessions#destroy", as: :logout
    get    :login,  to: "sessions#new",     as: :login
    post   :login,  to: "sessions#create"

    # signup & activation
    get  :signup, to: "users#new", as: :signup
    post :signup, to: "users#create"
    get "/users/:token/activate", to: "users#activate", as: :activate,
      constraints: {token: /[A-z0-9]+/}

    # reset password
    resources :password_resets,
      param:  :token,
      except: [:index, :show, :destroy],
      constraints: {token: /[A-z0-9]+/}

    # versions
    constraints id: /[0-9]+/, type: /b|l/ do
      get  "/v/:id/:type/revert", to: "versions#revert", as: :revert_version,
        constraints: RevertConstraint.new
      post "/v/:id/:type/revert", to: "versions#restore",
        constraints: RevertConstraint.new
    end

    # pages
    get :introduction, to: "pages#introduction"
    get :changelog,    to: "pages#changelog"
    get :syntax,       to: "pages#syntax"
  end

  # nodes and notes
  constraints id: /[0-9]+/ do
    constraints format: /html|txt/ do
      resources :nodes, path: "b", shallow: true, only: :index
    end

    resources :nodes, path: "b", shallow: true, only: :none do
      constraints format: "html" do
        resources :nodes, path: "b",
          except: [:index, :destroy, :show], with: [:delete]
        resources :notes, path: "l",
          except: [:index, :destroy, :show], with: [:delete]
      end

      constraints format: /html|txt/ do
        resources :nodes, path: "b", only: [:show]
        resources :notes, path: "l", only: [:show]
      end
    end
  end

  constraints format: "xml" do
    get :sitemap, to: "sitemap#index"
  end

  root "pages#index"
end

app/views/pages/changelog.html.slim
#pages.changelog
  h2 Changelog
  .links
    | >&nbsp;
    = link_to "return to the top", root_path

  h3 Recent changes
  ul.changelog
    li.entry
      | Improve unorderd list style (stylesheet)
      | &nbsp;
      span.released 2015-01-22
    li.entry
      | Improve error pages :p
      | &nbsp;
      span.released 2015-01-18
    li.entry
      | Security fix (upgrade framework)
      | &nbsp;
      span.released 2014-12-03
    li.entry
      | Blank line validation and title handling improvement
      | &nbsp;
      span.released 2014-09-17
      ul
        li
          | First entry is always treated as title
          ul
            li All lines are entry (Removed specialized title and second blank line)
            li See #{link_to("Syntax page", syntax_path)}
        li Dis-allow blank line
    li.entry
      | Indent/Unindent operator support
      | &nbsp;
      span.released 2014-08-24
      ul
        li
          | Add operator + (plus sign) and - (minus sign)
          ul
            li Use + for indent, - for unindent before bullet (like: `-*`)
        li Create #{link_to("Syntax page", syntax_path)}
    li.entry
      | Alpha release
      | &nbsp;
      span.released 2014-05-05
      ul
        li Fix various stuff of production environment
        li Publish as #{link_to("https://spruce-tree.net/", root_path)}
    li.entry
      | Deployment
      | &nbsp;
      span.released 2014-04-20
      ul
        li Introduce automation flow for deploy and infra setup
    li.entry
      | Version Management
      | &nbsp;
      span.released 2014-03-30
      ul
        li LifeCycle Tracking (undo & redo)
    li.entry
      | Background Job
      | &nbsp;
      span.released 2014-03-20
      ul
        li Add worker for background jobs
    li.entry
      | Navigation for text-browser
      | &nbsp;
      span.released 2014-03-19
      ul
        li Delete & Logout link without JavaScript
    li.entry
      | First release!
      | &nbsp;
      span.released 2014-03-18
      ul
        li Authentication, Activation
        li Node(branch), Note(leaf)

app/views/pages/index.html.slim
#pages.index
  h2.text Let's spruce up messy thoughts.
  ul.links
    li
      - if current_user && @root
        = link_to "Outlines", nodes_path
      - else
        | Outlines
      ul
        li Create issues, chapters or just items.
    li
      = link_to "Introduction", introduction_path
      ul
        li What's this?
    li
      = link_to "Changelog", changelog_path
      ul
        li History of Spruce
    li
      span.strike Plans
      ul
        li Free, for now :)

app/views/pages/introduction.html.slim
#pages.introduction
  h2 Introduction
  .links
    | >&nbsp;
    = link_to "return to the top", root_path

  h3 What's Spruce
  ul.descriptions
    li
      strong Simple Outliner
      ul
        li Textarea (Leaf) only
        li You can draw tree with only text
        li Moving syntax support such as `<` or `-` (under development)
    li
      strong Directory Organizer
      ul
        li Node (Branch) tree viewer
        li You can put outlines into tree like filesystem

  h3 Features
  ul.features
    li Undo/Redo support
    li SSL support
    li Expand view with Ajax
    li Text browser friendly design
    li Simple syntax

  h3 Syntax
  p.syntax
    | See&nbsp;
    = link_to "syntax page", syntax_path

  h3 Libraries
  ul.libraries
    li
      = link_to "SetCursorLine", "https://github.com/grauwoelfchen/set-cursor-line"
      ul
        li jQuery Plugin, Underline in Textarea
    li
      = link_to "SetNumber jQuery Plugin", "https://github.com/grauwoelfchen/set-number"
      ul
        li jQuery Plugin, Line number in Textarea
    li
      = link_to "Lilac", "https://github.com/grauwoelfchen/lilac"
      ul
        li Rubygems, List text converter
    li
      = link_to "Foreman Runit Template", "https://github.com/grauwoelfchen/foreman-runit-template"
      ul
        li Capistrano task template

  h3 Screenshots
  p.screenshots Do you use text-browser? No problem, it is also supported ;)
  ul.screenshots
    li= screenshot "spruce-branch-with-firefox.png", "branch with firefox"
    li= screenshot "spruce-leaf-with-firefox.png",   "leaf with firefox"
    li= screenshot "spruce-with-elinks.png",         "spruce with elinks"

  h3 Author
  p.author
    span.name Yasuhiro Asaka
    span.links
    | (
    = link_to "humans.txt", "/humans.txt"
    | ,&nbsp;
    = link_to "@grauwoelfchen",
      "https://twitter.com/grauwoelfchen", target: "_blank"
    | )
  p.note If you have any problem, please tell me :)

app/views/pages/syntax.html.slim
#pages.syntax
  h2 Syntax
  .links
    | >&nbsp;
    = link_to "return to the top", root_path

  h3 Rules
  ul.descriptions
    li
      strong Put the title
      ul
        li First line is treated as title
    li
      strong Start with bullet + a whitespace
      ul
        li Entry must be started with `* `
    li
      strong Indent with `  `
      ul
        li Indent must be 2 whitespaces

  h3 Operators
  ul.descriptions
    li
      strong `-` (minus sign)
      ul
        li Unindent one level
    li
      strong `+` (plus sign)
      ul
        li Indent one level

  h3 Example
  p e.g. indent with `+`
  pre.example.before
    | * Issues
        * foo
        +* bar
          * baz
        * qux
        * quux
  p after save, result:
  pre.example.after
    | * Issues
        * foo
          * bar
          * baz
        * qux
        * quux