config/routes.rb
Spruce::Application.routes.draw do
  constraints format: "html" do
    # authentication
    delete :logout, to: "sessions#destroy", as: :logout
    get    :login,  to: "sessions#new",     as: :login
    post   :login,  to: "sessions#create"

    # signup & activation
    get  :signup, to: "users#new", as: :signup
    post :signup, to: "users#create"
    get "/users/:token/activate", to: "users#activate", as: :activate,
      constraints: {token: /[A-z0-9]+/}

    # reset password
    resources :password_resets,
      param:  :token,
      except: [:index, :show, :destroy],
      constraints: {token: /[A-z0-9]+/}

    # versions
    constraints id: /[0-9]+/, type: /b|l/ do
      get  "/v/:id/:type/revert", to: "versions#revert", as: :revert_version,
        constraints: RevertConstraint.new
      post "/v/:id/:type/revert", to: "versions#restore",
        constraints: RevertConstraint.new
    end

    # pages
    get :introduction, to: "pages#introduction"
    get :changelog,    to: "pages#changelog"
    get :syntax,       to: "pages#syntax"
  end

  # nodes and notes
  constraints id: /[0-9]+/ do
    constraints format: /html|txt/ do
      resources :nodes, path: "b", shallow: true, only: :index
    end

    resources :nodes, path: "b", shallow: true, only: :none do
      constraints format: "html" do
        resources :nodes, path: "b",
          except: [:index, :destroy, :show], with: [:delete]
        resources :notes, path: "l",
          except: [:index, :destroy, :show], with: [:delete]
      end

      constraints format: /html|txt/ do
        resources :nodes, path: "b", only: [:show]
        resources :notes, path: "l", only: [:show]
      end
    end
  end

  constraints format: "xml" do
    get :sitemap, to: "sitemap#index"
  end

  root "pages#index"
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="title" content=(t "title", scope: "app")
    meta name="description" content=(t "description", scope: "app")
    title= t "title", scope: "app"
    = stylesheet_link_tag "application",
      media: "all",
      data:  {"turbolinks-track" => true}
    = yield :style
    = javascript_include_tag "application",
      data: {"turbolinks-track"=> true}
    = csrf_meta_tags
    link type="text/plain" rel="author" href="/humans.txt"
    = display_favicon_link Rails.env
    css:
      body {background-color:white;}
  body.application
    header
      .logo
        - logo = link_to root_path do
          = image_tag "spruce.png", size: "47x63"
        javascript:
          (function() {
            $("header > .logo").html($('<h2>#{logo}</h2>'));

          })();
      .container
        .content
          h1
            = link_to root_path do
              span Spruce
          .user
            - if current_user
              span= "Hi #{current_user.username}"
              | &nbsp;
              = button_to "Log out", logout_path, method: :delete
            - else
              - if current_page_in?(["sessions#new", "sessions#create"])
                | Log in
              - else
                = link_to "Log in",  login_path
              | &nbsp;or&nbsp;
              - if current_page_in?(["users#new", "users#create"])
                | Sign up
              - else
                = link_to "Sign up", signup_path
    section
      #nav.nav
        .navs
      javascript:
        (function() {
          $("#nav > .navs").html($('<ul>\
            <li>#{current_user ? link_to("outlines", nodes_path) : link_to("top", root_path)}</li>\
            <li>#{link_to("syntax", syntax_path)}</li>\
          </ul>'));
        })();
      .container
        .content 
          - if flash.any? && flash.notice
            = render "shared/flash", flash: flash
          == yield
    footer